In [1]:
import numpy as np
import pandas as pd
np.random.seed(42)

In [2]:
# Create a monthly date index
dates = pd.date_range(start="2024-01-01", periods=12, freq="MS")

# Simulate monthly sales (base + random noise)
base = 200
trend = np.linspace(0, 60, 12)  # simple upward trend
noise = np.random.normal(0, 10, 12)
sales = base + trend + noise

# Wrap into a pandas Series for convenience
sales_series = pd.DataFrame({'Date': dates, 'Sales A': sales})
sales_series

         Date     Sales A
0  2024-01-01  204.967142
1  2024-02-01  204.071902
2  2024-03-01  217.385976
3  2024-04-01  231.593935
4  2024-05-01  219.476648
5  2024-06-01  224.931358
6  2024-07-01  248.519401
7  2024-08-01  245.856165
8  2024-09-01  238.941620
9  2024-10-01  254.516510
10 2024-11-01  249.911278
11 2024-12-01  255.342702

In [3]:
noise_b = np.random.normal(0, 12, 12)
sales_b = base + trend * 0.6 + 25 + noise_b
sales_series['Sales B'] = sales_b
sales_series

         Date     Sales A     Sales B
0  2024-01-01  204.967142  227.903547
1  2024-02-01  204.071902  205.313364
2  2024-03-01  217.385976  210.846441
3  2024-04-01  231.593935  228.070731
4  2024-05-01  219.476648  225.936936
5  2024-06-01  224.931358  245.134604
6  2024-07-01  248.519401  233.740075
7  2024-08-01  245.856165  230.961446
8  2024-09-01  238.941620  268.769603
9  2024-10-01  254.516510  251.745230
10 2024-11-01  249.911278  258.537611
11 2024-12-01  255.342702  243.903022

In [4]:
sales_series.to_csv('sales.csv', index=False)